apiVersion: batch/v1
kind: Job
metadata:
  name: akeneo-init
  labels:
    app.kubernetes.io/name: akeneo-init
    app.kubernetes.io/part-of: akeneo
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 180
  template:
    spec:
      containers:
        - name: akeneo-init
          image: {{ include "akeneo.image" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["/usr/local/bin/pim-init-db.sh"]
      restartPolicy: Never
