apiVersion: apps/v1
kind: Deployment
metadata:
  name: akeneo-queue-consumer
  labels:
    app.kubernetes.io/name: akeneo-queue-consumer
    app.kubernetes.io/version: {{ .Values.akeneo.version | quote }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: akeneo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: akeneo-queue-consumer
      app.kubernetes.io/version: {{ .Values.akeneo.version | quote }}
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: akeneo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: akeneo-queue-consumer
        app.kubernetes.io/version: {{ .Values.akeneo.version | quote }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: akeneo
    spec:
      containers:
      - name: akeneo
        image: {{ include "akeneo.image" . }}
        command: ["/app/bin/console"]
        args: ["akeneo:batch:job-queue-consumer-daemon", "--env=prod"]
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: APP_ENV
          value: prod
