apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-master
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/version: "6.5"
    app.kubernetes.io/component: database
    role: master
spec:
  serviceName: elasticsearch-master
  replicas: {{ .Values.elasticsearch.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elasticsearch
        app.kubernetes.io/version: "6.5"
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: akeneo
        role: master
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-master
        image: {{ .Values.elasticsearch.image }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "cluster.name"
          value: docker
        - name: "network.host"
          value: 0.0.0.0
        - name: "discovery.zen.minimum_master_nodes"
          value: "2"
        - name: "discovery.zen.ping.unicast.hosts"
          value: "elasticsearch-discovery-service"
        - name: "discovery.type"
          value: zen
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.elasticsearch.memory }} -Xmx{{ .Values.elasticsearch.memory }}"
        - name: TAKE_FILE_OWNERSHIP
          value: "1"
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        volumeMounts:
        - name: storage
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: {{ .Values.elasticsearch.storage.class }}
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: {{ .Values.elasticsearch.storage.size }}
