apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetes.io/part-of: akeneo
spec:
  ports:
  - port: 3306
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: akeneo
  clusterIP: None
