apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: "5.7"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: akeneo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/part-of: akeneo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/part-of: akeneo
    spec:
      containers:
      - image: {{ .Values.mysql.image }}
        args:
        - "--ignore-db-dir=lost+found"
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: akeneo
          - name: MYSQL_DATABASE
            value: akeneo
          - name: MYSQL_USER
            value: akeneo
          - name: MYSQL_PASSWORD
            value: akeneo
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
