apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app.kubernetes.io/part-of: akeneo
spec:
  storageClassName: {{ .Values.mysql.storage.class }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
