apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeneo.fullname" . }}-secret
  labels:
  {{- include "akeneo.labels" . | nindent 4 }}
data:
  APP_DATABASE_PASSWORD: {{ .Values.mysql.password | b64enc }}
