apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "akeneo.fullname" . }}-queue-consumer-deployment
  labels:
  {{- include "akeneo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.akeneo.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      name: {{ include "akeneo.name" . }}
      role: queue-consumer
  template:
    metadata:
      labels:
        {{- include "akeneo.labels" . | nindent 8 }}
        role: queue-consumer
    spec:
      containers:
        - name: php
          image: {{ include "akeneo.image" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["/app/bin/console"]
          args: ["akeneo:batch:job-queue-consumer-daemon"]
          envFrom:
            - configMapRef:
                name:  {{ include "akeneo.fullname" . }}-configmap
            - secretRef:
                name:  {{ include "akeneo.fullname" . }}-secret
          volumeMounts:
            - mountPath: /app/config/packages/prod/oneup_flysystem.yml
              name: config-files
              subPath: oneup_flysystem.yml
      volumes:
        - name: config-files
          configMap:
            name: {{ include "akeneo.fullname" . }}-files-configmap
