{{- if .Values.objectStorage.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "akeneo.fullname" . }}-minio-service
  labels:
    {{- include "akeneo.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}
    name: {{ include "akeneo.name" . }}
    role: minio
  ports:
  - name: http
    port: {{ .Values.objectStorage.minio.port }}
{{- end }}
