{{- if .Values.objectStorage.minio.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "akeneo.fullname" . }}-minio-pvc
  labels:
    {{- include "akeneo.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.objectStorage.minio.storage.class }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.objectStorage.minio.storage.size }}
{{- end }}
