apiVersion: v1
kind: Service
metadata:
  name: {{ include "akeneo.fullname" . }}-mysql-service
  labels:
  {{- include "akeneo.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}
    name: {{ include "akeneo.name" . }}
    role: mysql
  ports:
    - name: mysql
      port: 3306
