FROM php:7.4-fpm-bullseye as php

RUN echo "deb http://ftp.debian.org/debian bullseye-backports main" | tee /etc/apt/sources.list.d/backports.list \
    && apt-get update \
    && apt-get install -y \
    libfreetype6-dev \
    libicu-dev \
    libzip-dev \
    libmagickwand-dev \
    libsodium-dev \
    net-tools \
    libjpeg62-turbo-dev \
    libmcrypt-dev \
    libpng-dev \
    libxslt1-dev \
    unzip \
    wget \
    git

RUN docker-php-ext-configure \
    gd --with-jpeg=/usr/include/ --with-freetype=/usr/include/ \
  && docker-php-ext-install -j$(nproc) \
    bcmath \
    gd \
    intl \
    json \
    opcache \
    pcntl \
    pdo_mysql \
    soap \
    sockets \
    xsl \
    zip \
  && pecl install apcu \
  && docker-php-ext-enable apcu \
  && pecl install imagick \
  && docker-php-ext-enable imagick \
  && pecl install redis \
  && docker-php-ext-enable redis

RUN rm -rf /tmp/* /var/lib/tmp/* /var/run/* && mkdir -p -m 777 /tmp /var/lib/tmp /var/run

FROM scratch as php-copier

COPY --from=php /usr/lib/aarch64-linux-gnu/libargon2.so.1 /usr/lib/aarch64-linux-gnu/libargon2.so.1
COPY --from=php /lib/aarch64-linux-gnu/libresolv.so.2 /lib/aarch64-linux-gnu/libresolv.so.2
COPY --from=php /lib/aarch64-linux-gnu/libreadline.so.8 /lib/aarch64-linux-gnu/libreadline.so.8
COPY --from=php /lib/aarch64-linux-gnu/libm.so.6 /lib/aarch64-linux-gnu/libm.so.6
COPY --from=php /lib/aarch64-linux-gnu/libdl.so.2 /lib/aarch64-linux-gnu/libdl.so.2
COPY --from=php /usr/lib/aarch64-linux-gnu/libxml2.so.2 /usr/lib/aarch64-linux-gnu/libxml2.so.2
COPY --from=php /usr/lib/aarch64-linux-gnu/libssl.so.1.1 /usr/lib/aarch64-linux-gnu/libssl.so.1.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1 /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libsqlite3.so.0 /usr/lib/aarch64-linux-gnu/libsqlite3.so.0
COPY --from=php /lib/aarch64-linux-gnu/libz.so.1 /lib/aarch64-linux-gnu/libz.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libcurl.so.4 /usr/lib/aarch64-linux-gnu/libcurl.so.4
COPY --from=php /usr/lib/aarch64-linux-gnu/libonig.so.5 /usr/lib/aarch64-linux-gnu/libonig.so.5
COPY --from=php /lib/aarch64-linux-gnu/libc.so.6 /lib/aarch64-linux-gnu/libc.so.6
COPY --from=php /lib/aarch64-linux-gnu/ld-2.31.so /lib/ld-linux-aarch64.so.1
COPY --from=php /lib/aarch64-linux-gnu/ld-2.31.so /lib/aarch64-linux-gnu/ld-2.31.so
COPY --from=php /lib/aarch64-linux-gnu/libpthread.so.0 /lib/aarch64-linux-gnu/libpthread.so.0
COPY --from=php /lib/aarch64-linux-gnu/libtinfo.so.6 /lib/aarch64-linux-gnu/libtinfo.so.6
COPY --from=php /usr/lib/aarch64-linux-gnu/libicuuc.so.67 /usr/lib/aarch64-linux-gnu/libicuuc.so.67
COPY --from=php /lib/aarch64-linux-gnu/liblzma.so.5 /lib/aarch64-linux-gnu/liblzma.so.5
COPY --from=php /usr/lib/aarch64-linux-gnu/libnghttp2.so.14 /usr/lib/aarch64-linux-gnu/libnghttp2.so.14
COPY --from=php /usr/lib/aarch64-linux-gnu/libidn2.so.0 /usr/lib/aarch64-linux-gnu/libidn2.so.0
COPY --from=php /usr/lib/aarch64-linux-gnu/librtmp.so.1 /usr/lib/aarch64-linux-gnu/librtmp.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libssh2.so.1 /usr/lib/aarch64-linux-gnu/libssh2.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libpsl.so.5 /usr/lib/aarch64-linux-gnu/libpsl.so.5
COPY --from=php /usr/lib/aarch64-linux-gnu/libgssapi_krb5.so.2 /usr/lib/aarch64-linux-gnu/libgssapi_krb5.so.2
COPY --from=php /usr/lib/aarch64-linux-gnu/libldap_r-2.4.so.2 /usr/lib/aarch64-linux-gnu/libldap_r-2.4.so.2
COPY --from=php /usr/lib/aarch64-linux-gnu/liblber-2.4.so.2 /usr/lib/aarch64-linux-gnu/liblber-2.4.so.2
COPY --from=php /usr/lib/aarch64-linux-gnu/libbrotlidec.so.1 /usr/lib/aarch64-linux-gnu/libbrotlidec.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libicudata.so.67 /usr/lib/aarch64-linux-gnu/libicudata.so.67
COPY --from=php /usr/lib/aarch64-linux-gnu/libstdc++.so.6 /usr/lib/aarch64-linux-gnu/libstdc++.so.6
COPY --from=php /lib/aarch64-linux-gnu/libgcc_s.so.1 /lib/aarch64-linux-gnu/libgcc_s.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libunistring.so.2 /usr/lib/aarch64-linux-gnu/libunistring.so.2
COPY --from=php /usr/lib/aarch64-linux-gnu/libgnutls.so.30 /usr/lib/aarch64-linux-gnu/libgnutls.so.30
COPY --from=php /usr/lib/aarch64-linux-gnu/libhogweed.so.6 /usr/lib/aarch64-linux-gnu/libhogweed.so.6
COPY --from=php /usr/lib/aarch64-linux-gnu/libnettle.so.8 /usr/lib/aarch64-linux-gnu/libnettle.so.8
COPY --from=php /usr/lib/aarch64-linux-gnu/libgmp.so.10 /usr/lib/aarch64-linux-gnu/libgmp.so.10
COPY --from=php /usr/lib/aarch64-linux-gnu/libgcrypt.so.20 /usr/lib/aarch64-linux-gnu/libgcrypt.so.20
COPY --from=php /usr/lib/aarch64-linux-gnu/libkrb5.so.3 /usr/lib/aarch64-linux-gnu/libkrb5.so.3
COPY --from=php /usr/lib/aarch64-linux-gnu/libk5crypto.so.3 /usr/lib/aarch64-linux-gnu/libk5crypto.so.3
COPY --from=php /lib/aarch64-linux-gnu/libcom_err.so.2 /lib/aarch64-linux-gnu/libcom_err.so.2
COPY --from=php /usr/lib/aarch64-linux-gnu/libkrb5support.so.0 /usr/lib/aarch64-linux-gnu/libkrb5support.so.0
COPY --from=php /usr/lib/aarch64-linux-gnu/libsasl2.so.2 /usr/lib/aarch64-linux-gnu/libsasl2.so.2
COPY --from=php /usr/lib/aarch64-linux-gnu/libbrotlicommon.so.1 /usr/lib/aarch64-linux-gnu/libbrotlicommon.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libp11-kit.so.0 /usr/lib/aarch64-linux-gnu/libp11-kit.so.0
COPY --from=php /usr/lib/aarch64-linux-gnu/libtasn1.so.6 /usr/lib/aarch64-linux-gnu/libtasn1.so.6
COPY --from=php /lib/aarch64-linux-gnu/libgpg-error.so.0 /lib/aarch64-linux-gnu/libgpg-error.so.0
COPY --from=php /lib/aarch64-linux-gnu/libkeyutils.so.1 /lib/aarch64-linux-gnu/libkeyutils.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libffi.so.7 /usr/lib/aarch64-linux-gnu/libffi.so.7
COPY --from=php /lib/aarch64-linux-gnu/librt.so.1 /lib/aarch64-linux-gnu/librt.so.1
COPY --from=php /usr/local/bin/php /usr/local/bin/php
COPY --from=php /usr/local/sbin/php-fpm /usr/local/sbin/php-fpm
COPY --from=php /usr/local/etc /usr/local/etc
COPY --from=php /usr/local/include/php /usr/local/include/php
COPY --from=php /usr/local/lib/php/extensions /usr/local/lib/php/extensions
# GD
COPY --from=php /usr/lib/aarch64-linux-gnu/libpng16.so.16 /usr/lib/aarch64-linux-gnu/libpng16.so.16
COPY --from=php /usr/lib/aarch64-linux-gnu/libjpeg.so.62 /usr/lib/aarch64-linux-gnu/libjpeg.so.62
COPY --from=php /usr/lib/aarch64-linux-gnu/libfreetype.so.6 /usr/lib/aarch64-linux-gnu/libfreetype.so.6
# Imagick
COPY --from=php /usr/lib/aarch64-linux-gnu/libgomp.so.1 /usr/lib/aarch64-linux-gnu/libgomp.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libMagickWand-6.Q16.so.6 /usr/lib/aarch64-linux-gnu/libMagickWand-6.Q16.so.6
COPY --from=php /usr/lib/aarch64-linux-gnu/libMagickCore-6.Q16.so.6 /usr/lib/aarch64-linux-gnu/libMagickCore-6.Q16.so.6
COPY --from=php /usr/lib/aarch64-linux-gnu/libX11.so.6 /usr/lib/aarch64-linux-gnu/libX11.so.6
COPY --from=php /usr/lib/aarch64-linux-gnu/liblcms2.so.2 /usr/lib/aarch64-linux-gnu/liblcms2.so.2
COPY --from=php /usr/lib/aarch64-linux-gnu/liblqr-1.so.0 /usr/lib/aarch64-linux-gnu/liblqr-1.so.0
COPY --from=php /usr/lib/aarch64-linux-gnu/libfftw3.so.3 /usr/lib/aarch64-linux-gnu/libfftw3.so.3
COPY --from=php /usr/lib/aarch64-linux-gnu/libfontconfig.so.1 /usr/lib/aarch64-linux-gnu/libfontconfig.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libXext.so.6 /usr/lib/aarch64-linux-gnu/libXext.so.6
COPY --from=php /lib/aarch64-linux-gnu/libbz2.so.1.0 /lib/aarch64-linux-gnu/libbz2.so.1.0
COPY --from=php /usr/lib/aarch64-linux-gnu/libltdl.so.7 /usr/lib/aarch64-linux-gnu/libltdl.so.7
COPY --from=php /usr/lib/aarch64-linux-gnu/libxcb.so.1 /usr/lib/aarch64-linux-gnu/libxcb.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0 /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
COPY --from=php /lib/aarch64-linux-gnu/libexpat.so.1 /lib/aarch64-linux-gnu/libexpat.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libuuid.so.1 /usr/lib/aarch64-linux-gnu/libuuid.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libXau.so.6 /usr/lib/aarch64-linux-gnu/libXau.so.6
COPY --from=php /usr/lib/aarch64-linux-gnu/libXdmcp.so.6 /usr/lib/aarch64-linux-gnu/libXdmcp.so.6
COPY --from=php /lib/aarch64-linux-gnu/libpcre.so.3 /lib/aarch64-linux-gnu/libpcre.so.3
COPY --from=php /usr/lib/aarch64-linux-gnu/libbsd.so.0 /usr/lib/aarch64-linux-gnu/libbsd.so.0
COPY --from=php /usr/lib/aarch64-linux-gnu/libmd.so.0 /usr/lib/aarch64-linux-gnu/libmd.so.0
# Intl
COPY --from=php /usr/lib/aarch64-linux-gnu/libicuio.so.67 /usr/lib/aarch64-linux-gnu/libicuio.so.67
COPY --from=php /usr/lib/aarch64-linux-gnu/libicui18n.so.67 /usr/lib/aarch64-linux-gnu/libicui18n.so.67
# Sodium
COPY --from=php /usr/lib/aarch64-linux-gnu/libsodium.so.23 /usr/lib/aarch64-linux-gnu/libsodium.so.23
# XSL
COPY --from=php /usr/lib/aarch64-linux-gnu/libexslt.so.0 /usr/lib/aarch64-linux-gnu/libexslt.so.0
COPY --from=php /usr/lib/aarch64-linux-gnu/libxslt.so.1 /usr/lib/aarch64-linux-gnu/libxslt.so.1
# ZIP
COPY --from=php /usr/lib/aarch64-linux-gnu/libzip.so.4 /usr/lib/aarch64-linux-gnu/libzip.so.4

ADD etc/passwd /etc/passwd
ADD etc/group /etc/group
ADD usr/local/etc/php-fpm.d/www.conf /usr/local/etc/php-fpm.d/www.conf
ADD usr/local/etc/php-fpm.conf /usr/local/etc/php-fpm.conf
ADD app/index.php /app/index.php

COPY --from=php /tmp /tmp
COPY --from=php /var/lib/tmp /var/lib/tmp
COPY --from=php /var/run /var/run

FROM scratch

COPY --from=php-copier / /

ENTRYPOINT ["/usr/local/sbin/php-fpm"]
