apiVersion: apps/v1
kind: Deployment
metadata:
  name: akeneo-queue-consumer
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: akeneo-queue-consumer
    app.kubernetes.io/version: "3.1"
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: akeneo-queue-consumer
      app.kubernetes.io/version: "3.1"
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: akeneo-queue-consumer
        app.kubernetes.io/version: "3.1"
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: akeneo
        image: {{ .Values.akeneo.image }}
        command: ["/app/bin/console"]
        args: ["akeneo:batch:job-queue-consumer-daemon", "--env=prod"]
        imagePullPolicy: Always
        env:
        - name: APP_ENV
          value: prod
