apiVersion: apps/v1
kind: Deployment
metadata:
  name: akeneo
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: akeneo
    app.kubernetes.io/version: "3.1"
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: akeneo
      app.kubernetes.io/version: "3.1"
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: akeneo
        app.kubernetes.io/version: "3.1"
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: akeneo
        image: {{ .Values.akeneo.image }}
        imagePullPolicy: Always
        env:
        - name: CLUSTER_NAME
          value: docker
        - name: APP_ENV
          value: prod
        ports:
        - containerPort: 8080
          name: http
        #lifecycle:
        #  postStart:
        #    exec:
        #      command: ["sh", "-c", "/app/bin/console d:s:u --force"]
