apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None
