{{- if not .Values.elasticsearch.external }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "akeneo.fullname" . }}-es-service
  labels:
    {{- include "akeneo.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}
    name: {{ include "akeneo.name" . }}
    role: es-master
  ports:
  - name: http
    port: 9200
{{- end }}
