{{- if .Values.objectStorage.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akeneo.fullname" . }}-minio-secret
  labels:
    {{- include "akeneo.labels" . | nindent 4 }}
data:
  MINIO_ROOT_USER: {{ .Values.objectStorage.minio.username | b64enc }}
  MINIO_ROOT_PASSWORD: {{ .Values.objectStorage.minio.password | b64enc }}
{{- end }}
