apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "akeneo.fullname" . }}-es-statefulset
  labels:
    {{- include "akeneo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      name: {{ include "akeneo.name" . }}
      role: es-master
  template:
    metadata:
      labels:
        {{- include "akeneo.labels" . | nindent 8 }}
        role: es-master
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: {{ .Values.elasticsearch.image }}
        env:
        - name: "cluster.name"
          value: {{ include "akeneo.fullname" . }}-es-cluster
        - name: "network.host"
          value: 0.0.0.0
{{/*        - name: "discovery.zen.minimum_master_nodes"*/}}
{{/*          value: {{ .Values.elasticsearch.minMasterNodes | quote }}*/}}
{{/*        - name: "discovery.zen.ping.unicast.hosts"*/}}
{{/*          value: {{ include "akeneo.fullname" . }}-es-discovery-service.{{ .Release.Namespace }}.svc.cluster.local*/}}
        - name: "discovery.type"
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.elasticsearch.memory }} -Xmx{{ .Values.elasticsearch.memory }}"
        - name: TAKE_FILE_OWNERSHIP
          value: "1"
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          httpGet:
            port: 9200
        livenessProbe:
          initialDelaySeconds: 90
          periodSeconds: 10
          httpGet:
            port: 9200
            path: /_search?size=0
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        volumeMounts:
        - name: storage
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: {{ .Values.elasticsearch.storage.class }}
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: {{ .Values.elasticsearch.storage.size }}
